# Generated by Django 5.2.9 on 2026-02-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_curator', '0006_rename_author_intro_aireviewanalysis_author_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireviewanalysis',
            name='author_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
